### ISSUE TITLE
Refactor Interviews

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/interview#1]
Tasks:
- [x] Generalize the QuestionNotes component (#19) to work with the following (make sure they now work with the new format of questions that are stored in Firebase, will need to mock data until other PRs are closed):
    - [x] Overview
    - [x] Resume
    - [x] Submit
- [x] Load interview room automatically (use room,js in `/pages`, so url will be upe.bu.edu/interview/room)
    - [x] Timeslot will have interviewer info, applicant info, and ~~level~~. Use this to initialize the room automatically
    - [x] When an interviewer loads the page, show them all the timeslots they are a part of for that day. They can hop in a room early and chill there
    - [x] Once the timeslot time arrives, the interviewer can start the session (don't start automatically in case they're prepping/talking)
    - [x] When an applicant loads the page, it won't let them in until the interviewer starts it (tell them the session hasn't started yet)
- [x] Use Stopwatch.js (shown only to interviewers) so they can keep track of time
- [x] Replace socket.io with Firebase to keep track of which question applicant is on. Create something like data/currentQuestion and store a doc that has the applicants current question id, and the interviewers can subscribe to that doc for changes (dont put it inside another doc because thats more unnecessary data, try to keep subscription to just what you need)
- [x] Complete related tasks:
    - [x] #2
    - [x] #5
    - [x] #19
- [x] Delete when the above are done (as they'll no longer be needed):
    - [x] StartScreen.js
    - [x] JoinRoom.js

**Comment by ROODAY** [comment]
Related issues that need to be completed with this:
- #2 
- #5 
- #19

**Comment by ROODAY** [comment]
Use this to make sure people dont switch tabs 
https://coderwall.com/p/cwpdaw/how-to-tell-if-app-page-has-focus

**Comment by vitorvicente** [comment]
https://github.com/serkanyersen/ifvisible.js

**Comment by ROODAY** [comment]
- Remove localstorage for tab key and current interview after interview closes

**Comment by ROODAY** [comment]
Merged in #80
