### ISSUE TITLE
Incorporate SendGrid for emails

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/interview#22]
Create functions on the server using the [SendGrid API](https://sendgrid.com/) to send emails. These emails can include application received receipts, timeslot confirmations, accepted/rejected results, etc. UPE has a SendGrid account, ask @ROODAY for an API key.

**Comment by vitorvicente** [comment]
- [ ] Create a general api function that allows for the sending of emails with input for "content" and "recipients"

- [ ] Create an api function for application receipt
- [ ] Create an api function for timeslot confirmation
- [ ] Create an api function for accepted/rejected

**Comment by vitorvicente** [comment]
app.post functions setup, just need to create the templates on SendGrid & put in the API Key, for which there is currently a placeholder in sendgrid.env

**Comment by vitorvicente** [comment]
This is done, or will be done in other issues posted here on Github, closing this one
