### ISSUE TITLE
Add deliberation page

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/interview#48]
Tasks
- [x] Page condition: must have have `recruitmentteam` role
- [x] If user is an Admin, they have option to open/close deliberations (if closed it should tell members that deliberations aren't happening right now). Will want to add a listener so if someone is on the page and an admin opens it, theyll update accordingly
- [x] ~~On page init do 2 things: 1) Use a transaction to increment number of active users viewing deliberation (also add a willUnmount that decrements, make sure the decrement works, will probably have to add cases for window before unload etc). 2) Get list of interviews (make sure to store id as well as data)~~ Outdated
- [x] Compute summary statistics (average question scores by level, by grad year) (look at the last seasons slides as reference for statistics) We could even do summary stats per question per level (i.e. average score for question id X in level Y, or grad year Z)
- [x] Sort them according to some criteria (level? graduation year?). Have some sidebar that everyone can see that shows the order of people to vote on, and current person (so people know where they are/how many people are left)
- [x] For each interview, fetch applicant info (all in their application) and display it (resume too since each person can be on this page and read at their pace). Display interviewer names. Display average question score of applicant along with summary stats for comparison. Display interviewer notes
- [x] Admins can see sidepanel that lets them start a vote for the current applicant. Show number of users who's voted out of total users viewing
- [x] Admins can then press a button to end the vote (hopefully they do it after everyone votes), and move on to the next person (should we show results right after a vote, or only until after all votes?)
- [x] Results emails should tell people results in the email (instead of a link that takes them to the app to see results). If they got in, system should automatically convert all their user accounts to member accounts (remove `nonmember` role and add `upemember` role). Perhaps the congrats email can have a link to the main site profile page so people can check out their profile and edit it (does the main site allow them to upload their own pictures? Would ease work of admins, just tell people to upload professional images. In future seasons when you can meet in person, just tell them to update the images with the initiation photos when they get them. can distribute photos via google drive team)
- [x] Once everything's over, and people see results, admins can close deliberations and this will send out results to applicants (either send results immediately, or schedule them to send at a specific time)
- [x] For people who are rejected, remove the `applicant` role from them (don't worry about deleting applications/timeslots etc, as when next season starts you can just press the delete inquisitor data button to clear all that).

Stretch Goals
- [ ] Use google drive API and GitHub API (and any else we need) + Firebase Functions to automatically add new members to our team drive and github. We can ask them for a github/require they have one to apply so we have their username to do so (as cs kids they'll all have one eventually so might as well make it a requirement)

Data that will be needed:
- deliberations open/closed flag
- count of users viewing the deliberations page <- gotta make sure this is accurate for all cases (navigating away, closing page, reloading, etc)
- count of votes per applicant to determine results
- current applicant being viewed

Data that will exist (make dummy data for now)
- levelConfig (defines questions in a level, there will be a separate `questions` collection that holds all the questions and are pulled during interview session)
```
{ // levels are keys
  Easy: [
    {
      id: QUESTION ID, // id of the question to grab
      order: ORDER # // where to order it
    },
    ...
  ],
  Medium: [
    {
      id: QUESTION ID,
      order: ORDER #
    },
    ...
  ],
  Hard: [
    {
      id: QUESTION ID,
      order: ORDER #
    },
    ...
  ],
  ...
}
```
- interviews
```
{
  interviewers: {
    interview1UID: NAME VALUE,
    interview2UID: NAME VALUE
  },
  applicant: {
    uid: UID VALUE,
    name: NAME VALUE
  },
  level: LEVEL VALUE,
  scores: { // resume and final notes will be "questions" so theyll be here, score will be something like "N/A" or some value that we ignore for stats
    interview1UID: {
      question1Id: SCORE VALUE,
      question2Id: SCORE VALUE,
      ...
    },
    interview2UID: {
      question1Id: SCORE VALUE,
      question2Id: SCORE VALUE,
      ...
    }
  },
  notes: { // resume and final notes will be "questions" so theyll be here
    interview1UID: {
      question1Id: NOTES VALUE,
      question2Id: NOTES VALUE,
      ...
    },
    interview2UID: {
      question1Id: NOTES VALUE,
      question2Id: NOTES VALUE,
      ...
    }
  }
}
```
- applications
```
{
  responses: [ // can hard code grabbing of name, grad year, major/minor, resume since those ids will never change
    {
      id: application question id,
      name: application question name,
      order: order it appeared in application,
      type: type of question,
      value: Value user gave for question
    },
    ...
  ],
  semester: Semester-Year of this application
}
```

**Comment by vitorvicente** [comment]
@ROODAY Any specific reason why we need to keep track of how many people are currently viewing the page?

**Comment by vitorvicente** [comment]
- Added dummy data to firebase
- Made a complete Deliberation page for Applicants (only visible to those who have been accepted)
  - Prompt users to confirm their acceptance
  - Data form requesting socials & profile image
  - Give proper roles & set gradYear

**Comment by vitorvicente** [comment]
- Added even more dummy data to firebase
- Made the start of the Deliberation page for the Recruitment team
  - Sidebar for navigation between applications + Info page + admin control
  - Fetch & Organize All the required data
  - Display the data (not yet complete)

**Comment by vitorvicente** [comment]
- Admin Settings
  - See all applications
  - Close voting
  - Provide feedback
  - Close Deliberations
- Fixed Data
  - Fixed votingsClosed
  - Fixed deliberationsClosed
- General Bug Fixes

**Comment by vitorvicente** [comment]
Next goals, Second Deliberation:

- [ ] Allow all UPE Members to vote
- [ ] Require 3/4ths majority to pass
- [ ] Only provisionalMembers should be under vote
- [ ] Feedback form 2.0 FOR ALL DENIED
- [ ] Open/Close 2nd Deliberation
- [ ] Applicant view - see deliberations & feedback
- [ ] UPEMember view - See all applicants & vote (no need to re-display data this time)
